spring:
  application:
    name: zuul-server

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
zuul:
  routes:
    hello: 
      path:        /hello/**
      url:        http://user-greeting-service:9090/hello      