spring:
  application:
    name: greeting-service

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      
instance_no: 1